
package:
  name: s4
  version: 1.1

source:
  path: ../../
  #url: https://github.com/simplejson/simplejson/releases/download/{{ version }}/simplejson-{{ version }}.tar.gz
  # and otherwise fall back to archive: 
  #sha256: d58439c548433adcda98e695be53e526ba940a4b9c44fb9a05d92cd495cdd47f
  # sha256 is the preferred checksum -- you can get it for a file with:
  #  `openssl sha256 <file name>`.

build:
  number: 0
  skip: True  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python {{ python }}
    - setuptools
    - numpy {{ numpy }}
    - boost
    - suitesparse
    - mkl-devel [win]
    - openblas [unix]

  host:
    - python {{ python }}
    - numpy {{ numpy }}
    - boost
    - suitesparse
    - mkl-devel [win]
    - openblas [unix]

  run:
    - python {{ python }}
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('boost') }}
    - {{ pin_compatible('suitesparse') }}
    - {{ pin_compatible('mkl-devel') }} [win]
    - {{ pin_compatible('openblas') }} [unix]

test:
  imports:
    - S4

about:
  home: https://web.stanford.edu/group/fan/S4/index.html
  license: GPL-2.0
  license_family: GPL
  # license_file: LICENSE.txt
  summary: 'S4 (Stanford Stratified Structure Solver) Conda Package'

  # The remaining entries in this section are optional, but recommended.
  description: |
    A program for computing electromagnetic fields in periodic, layered
    structures, developed by Victor Liu (victorliu@alumni.stanford.edu) of the
    Fan group in the Stanford Electrical Engineering Department.
    See the S4 manual, in doc/index.html, for a complete
    description of the package and its user interface, as well as
    installation instructions, the license and copyright, contact
    addresses, and other important information.
  doc_url: https://web.stanford.edu/group/fan/S4/index.html
  dev_url: https://web.stanford.edu/group/fan/S4/index.html

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - marcus-o